apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-analytics
spec:
  replicas: 1
  selector:
    matchLabels: { app: ui-analytics }
  template:
    metadata:
      labels: { app: ui-analytics }
    spec:
      containers:
        - name: ui-analytics
          image: your-dockerhub-username/ui-analytics:latest
          ports: [{ containerPort: 4173 }]
---
apiVersion: v1
kind: Service
metadata:
  name: ui-analytics
spec:
  type: LoadBalancer
  selector: { app: ui-analytics }
  ports:
    - port: 80
      targetPort: 4173
