apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels: { app: url-shortener }
  template:
    metadata:
      labels: { app: url-shortener }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: url-shortener
          image: your-dockerhub-username/service-url-shortener:latest
          ports: [{ containerPort: 8080 }]
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener
spec:
  type: ClusterIP
  selector: { app: url-shortener }
  ports:
    - port: 80
      targetPort: 8080
